# Generated by Django 3.0.1 on 2020-01-11 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_title', models.CharField(max_length=100)),
                ('Movie_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Moviedirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=50)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='watch.Movies')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_uploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uploader_name', models.CharField(max_length=100)),
                ('Uploader', models.ManyToManyField(to='watch.Movies')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_downloader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Downloader_name', models.CharField(max_length=100)),
                ('Downloader', models.ManyToManyField(to='watch.Movies')),
            ],
        ),
    ]
