# Generated by Django 2.2.7 on 2020-01-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_description', models.TextField()),
                ('movie_file', models.FileField(upload_to='movies')),
                ('release_date', models.DateField(verbose_name='Release Date')),
            ],
        ),
        migrations.CreateModel(
            name='MovieUploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_name', models.CharField(max_length=100)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='watch.Movies')),
            ],
        ),
        migrations.CreateModel(
            name='MovieDownloader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloader_name', models.CharField(max_length=100)),
                ('downloader', models.ManyToManyField(to='watch.Movies')),
            ],
        ),
    ]
