# Generated by Django 3.0.1 on 2020-01-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_downloader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Downloader_name', models.CharField(max_length=100)),
                ('Downloader', models.ManyToManyField(to='watch.Movies')),
            ],
        ),
    ]
