# Generated by Django 2.2.7 on 2020-02-10 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseDate',
            fields=[
                ('movie_title', models.CharField(max_length=100)),
                ('release_date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='watch.Movies')),
            ],
        ),
    ]
