# Generated by Django 3.0.1 on 2020-01-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_movie_downloader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_uploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uploader_name', models.CharField(max_length=100)),
                ('Uploader', models.ManyToManyField(to='watch.Movies')),
            ],
        ),
    ]
